name: deploy-product

on:
  push:
    branches:
      - master
    paths:
      - 'projects/product/**'
      - './package.json'
      - './package-lock.json'
      - './angular.json'
      - './tsconfig.json'
      - '.github/workflows/product.yml'

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build-product

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET_NAME }} --recursive --dryrun --exclude "*" --include "product/latest/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-3"

      - run: aws s3 sync ./dist/product s3://${{ secrets.AWS_S3_BUCKET_NAME }}/product/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-3"

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/product/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-3"
